language: python

python:
    - 2.7
    - 3.5
    # This is just for "egg_info".  All other builds are explicitly given in the matrix

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

git:
  depth: 1

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --quiet --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - if [[ $TRAVIS_PYTHON_VERSION -eq 2.7 ]]; then
         pip -q install coveralls;
      fi
    - conda install --quiet --yes --file requirements.txt
    - python setup.py develop

script:
    - if [[ $TRAVIS_PYTHON_VERSION -eq 2.7 ]]; then
        coverage run test/test.py;
      else
        nosetests -v test/test.py;
      fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION -eq 2.7]]; then
        coveralls;
      fi
